"""initial

Revision ID: 171069641dcd
Revises: 
Create Date: 2024-03-08 22:53:11.403228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '171069641dcd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_topic_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_topic_id'], ['topics.topic_id'], ),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('topic_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topics')
    # ### end Alembic commands ###
